"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-local-development-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost,testserver,animation-manager-ktew.onrender.com",
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "animateurs",
    "storages",
]

AWS_ACCESS_KEY_ID = os.getenv("SUPABASE_S3_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("SUPABASE_S3_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("SUPABASE_S3_BUCKET", "Documents")
AWS_S3_ENDPOINT_URL = os.getenv(
    "SUPABASE_S3_ENDPOINT_URL",
    "https://qarqqpbstjhcjnmiyiye.storage.supabase.co/storage/v1/s3",
)
AWS_S3_REGION_NAME = os.getenv("SUPABASE_S3_REGION", "eu-west-1")
AWS_S3_ADDRESSING_STYLE = "path"
AWS_QUERYSTRING_AUTH = False
AWS_S3_CUSTOM_DOMAIN = os.getenv(
    "SUPABASE_S3_CUSTOM_DOMAIN",
    "qarqqpbstjhcjnmiyiye.supabase.co/storage/v1/object/public/Documents",
)
AWS_LOCATION = os.getenv("SUPABASE_S3_LOCATION", "")

# Stockage des documents uploadés.
#
# Ce choix est indépendant de DEBUG : un serveur Django lancé en local peut
# parfaitement envoyer les fichiers vers Supabase.
#
# Valeurs possibles :
# - auto  : utilise Supabase S3 lorsque les deux clés sont renseignées, sinon local ;
# - s3    : impose Supabase S3 et refuse de démarrer si la configuration manque ;
# - local : impose le dossier MEDIA_ROOT.
#
# Les tests utilisent toujours un stockage local isolé afin de ne jamais écrire
# dans le bucket Supabase pendant la suite de tests.
FILE_STORAGE_BACKEND = os.getenv("FILE_STORAGE_BACKEND", "auto").strip().lower()

if "test" in sys.argv:
    FILE_STORAGE_BACKEND = "local"

if FILE_STORAGE_BACKEND not in {"auto", "local", "s3"}:
    raise ValueError("FILE_STORAGE_BACKEND doit valoir 'auto', 'local' ou 's3'.")

_s3_is_configured = bool(AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)
if FILE_STORAGE_BACKEND == "auto":
    FILE_STORAGE_BACKEND = "s3" if _s3_is_configured else "local"

if FILE_STORAGE_BACKEND == "s3":
    if not _s3_is_configured:
        raise ValueError(
            "Le stockage Supabase S3 est activé, mais SUPABASE_S3_ACCESS_KEY "
            "ou SUPABASE_S3_SECRET_KEY est absent."
        )
    _default_storage = {"BACKEND": "storages.backends.s3.S3Storage"}
else:
    _default_storage = {"BACKEND": "django.core.files.storage.FileSystemStorage"}

# Réglages compatibles avec l'API S3 de Supabase.
AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = False
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_VERIFY = True

STORAGES = {
    "default": _default_storage,
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Utilisé uniquement avec FILE_STORAGE_BACKEND=local.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Les API du planning renvoient des volumes JSON importants. La compression
    # diminue le temps de transfert, en particulier sur les connexions distantes.
    'django.middleware.gzip.GZipMiddleware',
    # WhiteNoise doit rester actif sur Render, même si DEBUG a été laissé à True
    # par erreur dans les variables d'environnement. Sans lui, Gunicorn renvoie
    # une page HTML 404 pour chaque fichier /static/.
    "whitenoise.middleware.WhiteNoiseMiddleware",
]
MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'animateurs.middleware.ConnexionObligatoireMiddleware',
    'animateurs.middleware.MotDePasseProvisoireMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'animateurs.context_processors.droits_application',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Si les variables de connexion Postgres sont présentes (cas prod sur
# Render, ou dev avec un .env valide), on les utilise. Sinon on retombe
# automatiquement sur une base SQLite locale : ça permet de cloner le
# projet et de lancer `runserver` sans avoir à configurer Supabase, et
# ça évite le plantage au démarrage quand le .env est absent ou que le
# projet Supabase (offre gratuite) est en pause.
if os.getenv("DB_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
            # PostgreSQL est hébergé à distance : réutiliser la connexion évite
            # une négociation réseau + TLS à chaque requête HTTP Django.
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": {
                "sslmode": "require",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Itinéraires des sorties via les services publics de la Géoplateforme IGN.
# Aucune clé API n'est nécessaire ; les URLs restent configurables afin de
# pouvoir basculer proprement si le service public évolue.
ROUTING_PROVIDER = os.getenv("ROUTING_PROVIDER", "geoplateforme")
ROUTING_API_URL = os.getenv("ROUTING_API_URL", "https://data.geopf.fr/navigation/itineraire")
ROUTING_GEOCODING_URL = os.getenv("ROUTING_GEOCODING_URL", "https://data.geopf.fr/geocodage/search")
ROUTING_RESOURCE = os.getenv("ROUTING_RESOURCE", "bdtopo-osrm")
ROUTING_TIMEOUT_SECONDS = int(os.getenv("ROUTING_TIMEOUT_SECONDS", "8"))


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

PASSWORD_MIN_LENGTH = int(os.getenv("PASSWORD_MIN_LENGTH", "5"))

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": PASSWORD_MIN_LENGTH},
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = os.getenv('TIME_ZONE', 'Europe/Paris')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"


STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Version unique des ressources statiques pour invalider le cache navigateur.
# En production, WhiteNoise ajoute aussi des empreintes de contenu.
ASSET_VERSION = os.getenv("ASSET_VERSION", "20260731-clean-1").strip()


# Envoi d'e-mails aux salariés. En local, sans serveur SMTP configuré,
# Django affiche les messages dans la console. En production, EMAIL_HOST est
# obligatoire et le service refuse d'utiliser le backend de test.
EMAIL_HOST = os.getenv("EMAIL_HOST", "").strip()
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in {"1", "true", "yes", "on"}
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in {"1", "true", "yes", "on"}
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "20"))
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_HOST
    else "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Gestion animation <noreply@gestion-animation.local>",
).strip()
EMAIL_REPLY_TO = os.getenv("EMAIL_REPLY_TO", "").strip()


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Réservée à une future intégration de la Vigilance officielle. Elle n'est
# jamais transmise au navigateur et son absence n'empêche pas les prévisions.
METEOFRANCE_VIGILANCE_API_KEY = os.getenv("METEOFRANCE_VIGILANCE_API_KEY", "").strip()


# Durcissement production (activé automatiquement lorsque DEBUG=False).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() in {"1", "true", "yes", "on"}
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

LOGIN_URL = "/connexion/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/connexion/"

TESTING = "test" in sys.argv
