"""Façade de compatibilité des vues historiques.

Les implémentations sont réparties par domaine pour limiter la taille des
modules. Les imports publics restent disponibles ici afin de ne pas modifier
les routes ni les intégrations existantes.
"""

from .views_catalogue import (
    api_centre_detail,
    api_centres,
    api_centres_reordonner,
    api_groupe_detail,
    api_groupe_partage_detail,
    api_groupes,
    api_groupes_partages,
    api_groupes_reordonner,
    api_periode_scolaire_detail,
    api_periodes_scolaires,
    api_periodes_scolaires_importer,
    api_periodes_scolaires_previsualiser,
    api_qualification_detail,
    api_qualifications,
)
from .views_pages import (
    accueil,
    administration,
    api_tableau_de_bord,
    api_verification_export_planning,
    changer_mot_de_passe,
    documents,
    emails,
    employe_detail,
    employes,
    export_planning_excel,
    export_planning_pdf,
    gestion,
    mes_disponibilites,
    mon_planning,
    mon_profil,
    planning,
    recapitulatif,
)
from .views_planning import (
    api_affectation_create,
    api_affectation_detail,
    api_horaires_affectations_groupe,
    api_planning,
    api_planning_auto,
    api_planning_plage,
)
from .views_reporting import api_document_detail, api_documents, api_recapitulatif
from .views_staff import api_animateur_detail, api_animateurs, api_disponibilite_detail, api_disponibilites

__all__ = [
    "accueil",
    "administration",
    "api_affectation_create",
    "api_affectation_detail",
    "api_animateur_detail",
    "api_animateurs",
    "api_centre_detail",
    "api_centres",
    "api_centres_reordonner",
    "api_disponibilite_detail",
    "api_disponibilites",
    "api_document_detail",
    "api_documents",
    "api_groupe_detail",
    "api_groupe_partage_detail",
    "api_groupes",
    "api_groupes_partages",
    "api_groupes_reordonner",
    "api_horaires_affectations_groupe",
    "api_periode_scolaire_detail",
    "api_periodes_scolaires",
    "api_periodes_scolaires_importer",
    "api_periodes_scolaires_previsualiser",
    "api_planning",
    "api_planning_auto",
    "api_planning_plage",
    "api_qualification_detail",
    "api_qualifications",
    "api_recapitulatif",
    "api_tableau_de_bord",
    "api_verification_export_planning",
    "changer_mot_de_passe",
    "documents",
    "emails",
    "employe_detail",
    "employes",
    "export_planning_excel",
    "export_planning_pdf",
    "gestion",
    "mes_disponibilites",
    "mon_planning",
    "mon_profil",
    "planning",
    "recapitulatif",
]
