"""Façade de compatibilité des vues historiques.

Les implémentations sont réparties par domaine pour limiter la taille des
modules. Les imports publics restent disponibles ici afin de ne pas modifier
les routes ni les intégrations existantes.
"""

from .views_catalogue import (
    api_centre_detail,
    api_centres,
    api_centres_reordonner,
    api_groupe_detail,
    api_groupe_partage_detail,
    api_groupes,
    api_groupes_partages,
    api_groupes_reordonner,
    api_periode_scolaire_detail,
    api_calendrier_scolaire_enregistrer,
    api_calendrier_scolaire_previsualiser,
    api_sejours,
    api_periodes_scolaires,
    api_periodes_scolaires_importer,
    api_periodes_scolaires_previsualiser,
    api_qualification_detail,
    api_qualifications,
)
from .views_pages import (
    accueil,
    administration,
    api_mon_centre_affectation,
    api_tableau_de_bord,
    api_statut_preparation_semaine,
    api_verification_export_planning,
    changer_mot_de_passe,
    demandes_materiel,
    documents,
    emails,
    employe_detail,
    employes,
    export_planning_excel,
    export_planning_pdf,
    gestion,
    mes_disponibilites,
    mon_profil,
    planning,
    recapitulatif,
    temps_travail,
)
from .views_planning import (
    api_affectation_create,
    api_affectation_detail,
    api_horaires_affectations_groupe,
    api_planning,
    api_publication_planning,
    api_planning_auto,
    api_planning_plage,
)
from .views_reporting import (
    api_attribution_prime_detail,
    api_attributions_primes,
    api_document_detail,
    api_documents,
    api_prime_journaliere,
    api_recapitulatif,
    export_recapitulatif_excel,
    export_recapitulatif_paie_pdf,
)
from .views_staff import api_animateur_detail, api_animateurs, api_disponibilite_detail, api_disponibilites
from .views_worktime import api_conflits_reunion, api_preparation_travail, api_reunion_detail, api_reunions, api_temps_travail
from .views_formations import api_formation_cloture, api_formation_detail, api_formations, formations
from .views_contrats import api_contrat_detail, api_contrats, api_types_contrats_actifs
from .views_parametres import (
    api_baremes_cee,
    api_parametres,
    api_parametres_contrats,
    api_parametre_contrat_detail,
    api_parametres_paie,
    api_type_prime_detail,
    api_types_primes,
    parametres,
)
from .views_statuts import api_historique_statut_detail, api_historique_statuts

__all__ = [
    "accueil",
    "administration",
    "api_affectation_create",
    "api_affectation_detail",
    "api_animateur_detail",
    "api_animateurs",
    "api_historique_statut_detail",
    "api_historique_statuts",
    "api_contrat_detail",
    "api_contrats",
    "api_types_contrats_actifs",
    "api_centre_detail",
    "api_conflits_reunion",
    "api_centres",
    "api_centres_reordonner",
    "api_disponibilite_detail",
    "api_disponibilites",
    "api_document_detail",
    "api_documents",
    "api_groupe_detail",
    "api_groupe_partage_detail",
    "api_groupes",
    "api_groupes_partages",
    "api_groupes_reordonner",
    "api_horaires_affectations_groupe",
    "api_formation_detail",
    "api_formation_cloture",
    "api_formations",
    "api_periode_scolaire_detail",
    "api_calendrier_scolaire_enregistrer",
    "api_calendrier_scolaire_previsualiser",
    "api_sejours",
    "api_periodes_scolaires",
    "api_periodes_scolaires_importer",
    "api_periodes_scolaires_previsualiser",
    "api_planning",
    "api_publication_planning",
    "api_planning_auto",
    "api_planning_plage",
    "api_parametres",
    "api_parametres_contrats",
    "api_parametre_contrat_detail",
    "api_parametres_paie",
    "api_baremes_cee",
    "api_types_primes",
    "api_type_prime_detail",
    "api_qualification_detail",
    "api_qualifications",
    "api_preparation_travail",
    "api_prime_journaliere",
    "api_recapitulatif",
    "api_reunion_detail",
    "api_reunions",
    "api_mon_centre_affectation",
    "api_tableau_de_bord",
    "api_statut_preparation_semaine",
    "api_verification_export_planning",
    "api_temps_travail",
    "changer_mot_de_passe",
    "demandes_materiel",
    "documents",
    "emails",
    "employe_detail",
    "employes",
    "export_planning_excel",
    "export_planning_pdf",
    "export_recapitulatif_excel",
    "export_recapitulatif_paie_pdf",
    "formations",
    "gestion",
    "mes_disponibilites",
    "mon_profil",
    "planning",
    "parametres",
    "recapitulatif",
    "temps_travail",
]
