# Generated by Django 5.2.15 on 2026-07-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animateur',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='animateur',
            name='bafa',
        ),
        migrations.RemoveField(
            model_name='animateur',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='animateur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='animateur',
            name='surveillant_baignade',
        ),
        migrations.RemoveField(
            model_name='animateur',
            name='telephone',
        ),
    ]
