# Generated by Django 5.2.15 on 2026-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='animateur',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='animateurs.qualification'),
        ),
    ]
