# Generated by Django 5.2.15 on 2026-07-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0008_animateur_contact_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='effectif_cible',
            field=models.PositiveSmallIntegerField(default=1, help_text="Nombre d'animateurs souhaités par jour dans ce centre"),
        ),
    ]
