# Generated by Django 5.2.15 on 2026-07-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0019_evenements_journaliers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='disponibilite',
            name='dispo_fin_apres_debut',
        ),
        migrations.RemoveConstraint(
            model_name='evenement',
            name='unique_nom_equipe_par_centre',
        ),
        migrations.RemoveConstraint(
            model_name='evenement',
            name='equipe_horaires_coherents',
        ),
        migrations.RemoveIndex(
            model_name='affectation',
            name='aff_equipe_debut_idx',
        ),
        migrations.AlterField(
            model_name='animateur',
            name='evenement_preferee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animateurs_preferant', to='animateurs.evenement'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='effectif_cible',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='centre',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ordre d’affichage des lieux sur la page planning.'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='animateurs.centre', verbose_name='lieu'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='effectif_cible',
            field=models.PositiveSmallIntegerField(default=1, help_text='Nombre de personnes nécessaires chaque jour'),
        ),
        migrations.AddIndex(
            model_name='affectation',
            index=models.Index(fields=['evenement', 'debut'], name='aff_evenement_debut_idx'),
        ),
        migrations.AddConstraint(
            model_name='disponibilite',
            constraint=models.CheckConstraint(condition=models.Q(('debut__isnull', True), ('fin__isnull', True), ('fin__gte', models.F('debut')), _connector='OR'), name='dispo_fin_apres_debut'),
        ),
        migrations.AddConstraint(
            model_name='evenement',
            constraint=models.UniqueConstraint(fields=('centre', 'nom', 'debut', 'fin'), name='unique_evenement_lieu_periode'),
        ),
        migrations.AddConstraint(
            model_name='evenement',
            constraint=models.CheckConstraint(condition=models.Q(('debut__isnull', True), ('fin__isnull', True), ('fin__gte', models.F('debut')), _connector='OR'), name='evenement_fin_apres_debut'),
        ),
    ]
