# Generated by Django 5.2.15 on 2026-07-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0033_animateur_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='cle_unique',
            field=models.CharField(default='', editable=False, max_length=120),
        ),
    ]
