# Generated by Django 5.2.15 on 2026-07-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0053_preferences_centres_multiples_interdits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencecentre',
            name='est_prefere',
            field=models.BooleanField(default=False, help_text='Centre à privilégier lors du remplissage automatique.'),
        ),
    ]
