# Generated by Django 5.2.15 on 2026-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0056_supprimer_historiques_emails_et_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectifenfantsjour',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effectifenfantsjour',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
