# Generated by Django 5.2.15 on 2026-07-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0058_groupes_partages_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='categorie',
            field=models.ForeignKey(blank=True, limit_choices_to={'est_categorie': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomes', to='animateurs.qualification'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='est_categorie',
            field=models.BooleanField(default=False, help_text='Catégorie de besoin regroupant plusieurs diplômes (ex. Diplômé).'),
        ),
    ]
