# Generated by Django 5.2.15 on 2026-07-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0065_qualification_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animateur',
            name='couleur',
        ),
    ]
