# Generated by Django 5.2.15 on 2026-07-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0068_remove_affectation_est_flottant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('date', models.DateField(db_index=True)),
                ('destination', models.CharField(max_length=180)),
                ('mode_transport', models.CharField(blank=True, default='', max_length=100)),
                ('nombre_vehicules', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart_site', models.TimeField(blank=True, null=True)),
                ('heure_retour', models.TimeField(blank=True, null=True)),
                ('trajet_ramassage', models.TextField(blank=True, default='')),
                ('consignes_transport', models.TextField(blank=True, default='')),
                ('objectifs_pedagogiques', models.TextField(blank=True, default='')),
                ('consignes_encadrement', models.TextField(blank=True, default='')),
                ('organisation_maternels', models.TextField(blank=True, default='')),
                ('organisation_elementaires', models.TextField(blank=True, default='')),
                ('repas_gouter', models.TextField(blank=True, default='')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='sorties', to='animateurs.document')),
                ('responsable_elementaires', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_responsable_elementaires', to='animateurs.animateur')),
                ('responsable_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_responsable_general', to='animateurs.animateur')),
                ('responsable_maternels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_responsable_maternels', to='animateurs.animateur')),
            ],
            options={
                'ordering': ('date', 'nom'),
            },
        ),
        migrations.CreateModel(
            name='SortieLien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='animateurs.sortie')),
            ],
            options={
                'ordering': ('ordre', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SortieParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite_horaire', models.CharField(blank=True, default='', max_length=240)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations_sorties', to='animateurs.evenement')),
                ('sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='animateurs.sortie')),
            ],
            options={
                'ordering': ('evenement__centre__ordre', 'evenement__ordre', 'evenement__nom'),
            },
        ),
        migrations.AddField(
            model_name='sortie',
            name='groupes',
            field=models.ManyToManyField(related_name='sorties', through='animateurs.SortieParticipation', to='animateurs.evenement'),
        ),
        migrations.AddConstraint(
            model_name='sortieparticipation',
            constraint=models.UniqueConstraint(fields=('sortie', 'evenement'), name='unique_groupe_par_sortie'),
        ),
    ]
