# Generated by Django 5.2.15 on 2026-07-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0070_responsabilites_sortie_configurables'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortieresponsabilite',
            name='affectation_creee',
            field=models.ForeignKey(blank=True, help_text='Affectation ajoutée automatiquement lors de la nomination du responsable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsabilites_sorties_creees', to='animateurs.affectation'),
        ),
    ]
