# Generated by Django 5.2.15 on 2026-07-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0071_sortieresponsabilite_affectation_creee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='meteo_adresse',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sortie',
            name='meteo_code_departement',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='sortie',
            name='meteo_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='meteo_lieu_libelle',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='sortie',
            name='meteo_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
