# Generated by Django 5.2.15 on 2026-07-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("animateurs", "0072_sortie_meteo_adresse_sortie_meteo_code_departement_and_more")]

    operations = [
        migrations.CreateModel(
            name="SortieRenfort",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("affectation", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="renfort_sortie", to="animateurs.affectation")),
                ("sortie", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="renforts", to="animateurs.sortie")),
            ],
            options={"ordering": ("affectation__animateur__nom", "affectation__animateur__prenom", "id")},
        ),
    ]
