# Generated by Django 6.0.8 on 2026-08-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0092_participation_formation_presences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('cee', 'CEE'), ('cdd', 'CDD'), ('apprentissage', 'Apprentissage')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('taux_journalier_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_mensuel_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='animateurs.animateur')),
            ],
            options={
                'ordering': ('-date_debut', '-id'),
            },
        ),
    ]
