# Generated by Django 6.0.8 on 2026-08-18 13:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0093_contrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.SlugField(default='principale', editable=False, unique=True)),
                ('nom_structure', models.CharField(blank=True, max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('taux_indemnite_cp_cee', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='taux indemnité congés payés CEE')),
                ('prime_journaliere_maximale', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10000.00'))], verbose_name='prime journalière maximale')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'paramètres de structure',
                'verbose_name_plural': 'paramètres de structure',
            },
        ),
    ]
