# Generated by Django 6.0.8 on 2026-08-18 14:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def creer_primes_initiales(apps, schema_editor):
    ParametresStructure = apps.get_model("animateurs", "ParametresStructure")
    TypePrime = apps.get_model("animateurs", "TypePrime")
    structures = list(ParametresStructure.objects.all())
    if not structures:
        structures = [ParametresStructure.objects.create(cle="principale")]
    contrats = ["cee", "cdd", "apprentissage"]
    for structure in structures:
        TypePrime.objects.get_or_create(
            structure=structure,
            nom="Prime d’autonomie",
            defaults={
                "active": True,
                "mode_calcul": "jour",
                "type_montant": "variable_plafonne",
                "montant_maximum": structure.prime_journaliere_maximale,
                "contrats_eligibles": contrats,
                "tous_statuts": True,
            },
        )
        TypePrime.objects.get_or_create(
            structure=structure,
            nom="Prime de direction adjointe",
            defaults={
                "active": False,
                "mode_calcul": "jour",
                "type_montant": "fixe",
                "contrats_eligibles": contrats,
                "tous_statuts": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0094_parametresstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresstructure',
            name='adapter_taux_cee_changement_statut',
            field=models.BooleanField(default=True, verbose_name='adapter automatiquement le taux CEE au changement de statut'),
        ),
        migrations.CreateModel(
            name='BaremeCEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_journalier', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_effet', models.DateField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('statut', models.ForeignKey(limit_choices_to={'est_statut': True}, on_delete=django.db.models.deletion.PROTECT, related_name='baremes_cee', to='animateurs.qualification')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baremes_cee', to='animateurs.parametresstructure')),
            ],
            options={
                'ordering': ('statut__nom', '-date_effet', '-id'),
                'constraints': [models.UniqueConstraint(fields=('structure', 'statut', 'date_effet'), name='unique_bareme_cee_structure_statut_date')],
            },
        ),
        migrations.CreateModel(
            name='TypePrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('mode_calcul', models.CharField(choices=[('jour', 'Par jour'), ('semaine', 'Par semaine'), ('mois', 'Par mois'), ('forfait', 'Forfait')], default='jour', max_length=20)),
                ('type_montant', models.CharField(choices=[('fixe', 'Fixe'), ('variable_plafonne', 'Variable plafonné')], default='fixe', max_length=24)),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contrats_eligibles', models.JSONField(blank=True, default=list)),
                ('tous_statuts', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('statuts_eligibles', models.ManyToManyField(blank=True, limit_choices_to={'est_statut': True}, related_name='types_primes_eligibles', to='animateurs.qualification')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_primes', to='animateurs.parametresstructure')),
            ],
            options={
                'ordering': ('nom', 'id'),
                'constraints': [models.UniqueConstraint(fields=('structure', 'nom'), name='unique_type_prime_structure_nom')],
            },
        ),
        migrations.RunPython(creer_primes_initiales, migrations.RunPython.noop),
    ]
