# Generated by Django 6.0.8 on 2026-08-18 14:42

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def reprendre_statuts_actuels(apps, schema_editor):
    Animateur = apps.get_model("animateurs", "Animateur")
    Historique = apps.get_model("animateurs", "HistoriqueStatutAnimateur")
    date_reprise = timezone.localdate()
    entrees = []
    for animateur in Animateur.objects.prefetch_related("qualifications__statut"):
        statuts = {}
        for qualification in animateur.qualifications.all():
            statut = qualification if qualification.est_statut else qualification.statut
            if statut is not None:
                statuts[statut.pk] = statut
        if not statuts:
            continue
        statut = sorted(statuts.values(), key=lambda item: (item.nom.casefold(), item.pk))[0]
        entrees.append(Historique(
            animateur_id=animateur.pk,
            statut_id=statut.pk,
            date_effet=date_reprise,
            origine="reprise",
            date_effet_incertaine=True,
            commentaire="Date technique de reprise ; date réelle d’obtention inconnue.",
        ))
    Historique.objects.bulk_create(entrees, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0095_parametresstructure_adapter_taux_cee_changement_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStatutAnimateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_effet', models.DateField()),
                ('origine', models.CharField(choices=[('manuelle', 'Saisie manuelle'), ('formation', 'Formation'), ('reprise', 'Reprise technique')], default='manuelle', max_length=16)),
                ('date_effet_incertaine', models.BooleanField(default=False, help_text="Vrai pour une date technique de reprise qui n'est pas une date d'obtention connue.")),
                ('commentaire', models.CharField(blank=True, max_length=240)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='animateurs.animateur')),
                ('statut', models.ForeignKey(limit_choices_to={'est_statut': True}, on_delete=django.db.models.deletion.PROTECT, related_name='historiques_statut_animateurs', to='animateurs.qualification')),
            ],
            options={
                'ordering': ('-date_effet', '-id'),
                'constraints': [models.UniqueConstraint(fields=('animateur', 'date_effet'), name='unique_statut_animateur_date_effet')],
            },
        ),
        migrations.RunPython(reprendre_statuts_actuels, migrations.RunPython.noop),
    ]
