# Generated by Django 6.0.8 on 2026-08-18 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0096_historiquestatutanimateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributionPrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('mode_calcul', models.CharField(choices=[('jour', 'Par jour'), ('semaine', 'Par semaine'), ('mois', 'Par mois'), ('forfait', 'Forfait')], max_length=20)),
                ('montant_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commentaire', models.CharField(blank=True, max_length=240)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions_primes', to='animateurs.animateur')),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primes_attribuees', to=settings.AUTH_USER_MODEL)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions_primes', to='animateurs.centre')),
                ('type_prime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='animateurs.typeprime')),
            ],
            options={
                'ordering': ('-date_debut', 'animateur__prenom', 'animateur__nom', 'id'),
            },
        ),
    ]
