# Generated by Django 6.0.8 on 2026-08-18 17:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def reprendre_contrats_et_primes(apps, schema_editor):
    ParametresStructure = apps.get_model('animateurs', 'ParametresStructure')
    TypeContrat = apps.get_model('animateurs', 'TypeContrat')
    Contrat = apps.get_model('animateurs', 'Contrat')
    TypePrime = apps.get_model('animateurs', 'TypePrime')
    HistoriqueRemunerationContrat = apps.get_model('animateurs', 'HistoriqueRemunerationContrat')
    structure, _ = ParametresStructure.objects.get_or_create(cle='principale')
    definitions = (
        ('cee', 'CEE', 'cee_journalier', 10),
        ('cdd', 'CDD', 'mensualise', 20),
        ('apprentissage', 'Apprentissage', 'apprentissage', 30),
        ('permanent', 'Permanent', 'paie_habituelle', 40),
    )
    types = {}
    for code, nom, mode, ordre in definitions:
        item, _ = TypeContrat.objects.get_or_create(
            structure=structure, code=code,
            defaults={
                'nom': nom, 'mode_remuneration': mode, 'ordre': ordre,
                'actif': True, 'systeme': True,
            },
        )
        types[code] = item
    for contrat in Contrat.objects.all().iterator():
        type_ref = types.get(contrat.type_contrat)
        if type_ref:
            Contrat.objects.filter(pk=contrat.pk).update(type_contrat_ref=type_ref)
        if contrat.type_contrat == 'apprentissage' and contrat.salaire_mensuel_reference is not None:
            HistoriqueRemunerationContrat.objects.get_or_create(
                contrat=contrat, date_effet=contrat.date_debut,
                defaults={
                    'montant_mensuel': contrat.salaire_mensuel_reference,
                    'origine': 'manuel',
                    'commentaire': 'Reprise du salaire contractuel existant',
                },
            )
    for prime in TypePrime.objects.all().iterator():
        eligibles = [types[code] for code in (prime.contrats_eligibles or []) if code in types]
        prime.types_contrats_eligibles.set(eligibles)


def reprise_inverse(apps, schema_editor):
    # Les anciens champs restent renseignés : aucun retour destructif n'est nécessaire.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0097_attributionprime'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='annee_execution_initiale',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_effet_annee_execution',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='heures_annuelles_reference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='heures_hebdomadaires',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='heures_mensuelles_reference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='mode_remuneration',
            field=models.CharField(choices=[('salaire_fixe', 'Salaire fixe'), ('minimum_smic', 'Minimum SMIC automatique'), ('fixe_controle', 'Salaire fixe avec contrôle du minimum'), ('grille_auto', 'Minimum grille automatique'), ('grille_controle', 'Salaire contractuel avec contrôle du minimum')], default='salaire_fixe', max_length=24),
        ),
        migrations.AddField(
            model_name='contrat',
            name='mode_temps_travail',
            field=models.CharField(choices=[('non_renseigne', 'Non renseigné'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annualise', 'Annualisé / lissé')], default='non_renseigne', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.SlugField()),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('mode_remuneration', models.CharField(choices=[('cee_journalier', 'Journalier CEE'), ('mensualise', 'Mensualisé'), ('apprentissage', 'Apprentissage'), ('paie_habituelle', 'Paie habituelle / hors calcul')], max_length=24)),
                ('systeme', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_contrats', to='animateurs.parametresstructure')),
            ],
            options={
                'ordering': ('ordre', 'nom', 'id'),
            },
        ),
        migrations.AddField(
            model_name='contrat',
            name='type_contrat_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='animateurs.typecontrat'),
        ),
        migrations.AddField(
            model_name='typeprime',
            name='types_contrats_eligibles',
            field=models.ManyToManyField(blank=True, related_name='types_primes_eligibles', to='animateurs.typecontrat'),
        ),
        migrations.CreateModel(
            name='BaremeApprentissage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_effet', models.DateField()),
                ('annee_execution', models.PositiveSmallIntegerField()),
                ('age_minimum', models.PositiveSmallIntegerField()),
                ('age_maximum', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pourcentage_smic', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actif', models.BooleanField(default=True)),
                ('commentaire', models.CharField(blank=True, max_length=240)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baremes_apprentissage', to='animateurs.parametresstructure')),
            ],
            options={
                'ordering': ('-date_effet', 'annee_execution', 'age_minimum', 'id'),
                'constraints': [models.UniqueConstraint(fields=('structure', 'date_effet', 'annee_execution', 'age_minimum'), name='unique_bareme_apprentissage_tranche_date')],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueRemunerationContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_effet', models.DateField()),
                ('montant_mensuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('origine', models.CharField(choices=[('manuel', 'Manuel'), ('grille_automatique', 'Grille automatique'), ('ajustement', 'Ajustement')], default='manuel', max_length=24)),
                ('commentaire', models.CharField(blank=True, max_length=240)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_remunerations', to='animateurs.contrat')),
            ],
            options={
                'ordering': ('-date_effet', '-id'),
                'constraints': [models.UniqueConstraint(fields=('contrat', 'date_effet'), name='unique_remuneration_contrat_date')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceSMIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_effet', models.DateField()),
                ('montant_horaire', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('montant_mensuel_35h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('source', models.CharField(blank=True, max_length=160)),
                ('identifiant_externe', models.CharField(blank=True, max_length=160)),
                ('recupere_le', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=240)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_smic', to='animateurs.parametresstructure')),
            ],
            options={
                'ordering': ('-date_effet', '-id'),
                'constraints': [models.UniqueConstraint(fields=('structure', 'date_effet'), name='unique_smic_structure_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='typecontrat',
            constraint=models.UniqueConstraint(fields=('structure', 'code'), name='unique_type_contrat_structure_code'),
        ),
        migrations.RunPython(reprendre_contrats_et_primes, reprise_inverse),
    ]
