# Generated by Django 6.0.8 on 2026-08-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0098_contrats_referentiels_smic_apprentissage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
