# Generated by Django 5.2.15 on 2026-08-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0100_informationanimateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('classique', 'Document classique'), ('programme_activites', "Programme d'activités")], db_index=True, default='classique', max_length=32),
        ),
    ]
