# Generated by Django 6.0.8 on 2026-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0101_document_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitetravailcomplementaire',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitetravailcomplementaire',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitetravailcomplementaire',
            name='lieu',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
