# Generated by Django 6.0.8 on 2026-08-22 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0109_contraintes_groupes_par_accueil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresstructure',
            name='pourcentage_non_qualifies_maximum',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='parametresstructure',
            name='pourcentage_qualifies_minimum',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
