# Generated by Django 6.0.8 on 2026-08-23 17:33

import django.db.models.deletion
from django.db import migrations, models


def creer_fonctions_v1(apps, schema_editor):
    Fonction = apps.get_model('animateurs', 'FonctionOperationnelle')
    for code, nom, ordre in (
        ('directeur', 'Directrice / Directeur', 10),
        ('directeur_adjoint', 'Direction adjointe', 20),
        ('referent_site', 'Référente / Référent de site', 30),
    ):
        Fonction.objects.update_or_create(code=code, defaults={'nom': nom, 'ordre': ordre, 'active': True})


def supprimer_fonctions_v1(apps, schema_editor):
    apps.get_model('animateurs', 'FonctionOperationnelle').objects.filter(
        code__in=('directeur', 'directeur_adjoint', 'referent_site')
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0110_alter_parametresstructure_pourcentage_non_qualifies_maximum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonctionOperationnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=80)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('ordre', 'nom', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ResponsabiliteOperationnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('perimetre', models.CharField(choices=[('groupe', 'Groupe'), ('accueil', 'Accueil'), ('site', 'Site')], max_length=12)),
                ('bloque_affectation_animation', models.BooleanField(default=True)),
                ('fournit_temps_travail', models.BooleanField(default=True, help_text='La période constitue une présence propre, hors temps déjà fourni par une affectation.')),
                ('compte_dans_encadrement', models.BooleanField(default=False)),
                ('compte_dans_quotas_qualification', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('accueil_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsabilites_operationnelles', to='animateurs.accueilcentre')),
                ('affectation_source_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text="Trace de la ligne d'origine ; le lien actif est résolu par animateur, groupe et période.", null=True)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsabilites_operationnelles', to='animateurs.animateur')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsabilites_operationnelles', to='animateurs.centre')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsabilites_operationnelles', to='animateurs.evenement')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsabilites', to='animateurs.fonctionoperationnelle')),
            ],
            options={
                'ordering': ('debut', 'fonction__ordre', 'animateur__prenom', 'animateur__nom', 'id'),
                'indexes': [models.Index(fields=['animateur', 'debut', 'fin'], name='resp_anim_periode_idx'), models.Index(fields=['centre', 'debut', 'fin'], name='resp_site_periode_idx'), models.Index(fields=['accueil_centre', 'debut', 'fin'], name='resp_acc_periode_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gt', models.F('debut'))), name='responsabilite_fin_apres_debut'), models.CheckConstraint(condition=models.Q(models.Q(('accueil_centre__isnull', True), ('centre__isnull', True), ('evenement__isnull', False), ('perimetre', 'groupe')), models.Q(('accueil_centre__isnull', False), ('affectation_source_id__isnull', True), ('centre__isnull', True), ('evenement__isnull', True), ('perimetre', 'accueil')), models.Q(('accueil_centre__isnull', True), ('affectation_source_id__isnull', True), ('centre__isnull', False), ('evenement__isnull', True), ('perimetre', 'site')), _connector='OR'), name='responsabilite_perimetre_coherent'), models.UniqueConstraint(condition=models.Q(('affectation_source_id__isnull', False)), fields=('affectation_source_id',), name='responsabilite_unique_par_affectation_source')],
            },
        ),
        migrations.RunPython(creer_fonctions_v1, supprimer_fonctions_v1),
    ]
