# Generated by Django 6.0.8 on 2026-08-26 17:36

import django.db.models.deletion
from django.db import migrations, models


def configurer_responsabilites(apps, schema_editor):
    Qualification = apps.get_model("animateurs", "Qualification")
    ParametresStructure = apps.get_model("animateurs", "ParametresStructure")
    FonctionOperationnelle = apps.get_model("animateurs", "FonctionOperationnelle")
    FonctionOperationnelle.objects.filter(code="directeur").update(
        nom="Directrice générale / Directeur général"
    )
    FonctionOperationnelle.objects.filter(code="directeur_adjoint").update(
        nom="Directrice adjointe / Directeur adjoint"
    )
    FonctionOperationnelle.objects.filter(code="referent_site").update(
        nom="Référente / Référent de site"
    )
    bafa = Qualification.objects.filter(cle_unique="bafa titulaire").first()
    if bafa is None:
        bafa = Qualification.objects.filter(nom__iexact="BAFA titulaire").first()
    if bafa:
        ParametresStructure.objects.update(
            directeur_adjoint_qualification_requise=bafa,
            referent_site_qualification_requise=bafa,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0111_fonctions_responsabilites_operationnelles'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresstructure',
            name='directeur_adjoint_majorite_requise',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametresstructure',
            name='directeur_adjoint_qualification_requise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='structures_direction_adjointe', to='animateurs.qualification'),
        ),
        migrations.AddField(
            model_name='parametresstructure',
            name='directeur_general_majorite_requise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parametresstructure',
            name='directeur_general_qualification_requise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='structures_direction_generale', to='animateurs.qualification'),
        ),
        migrations.AddField(
            model_name='parametresstructure',
            name='referent_site_majorite_requise',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametresstructure',
            name='referent_site_qualification_requise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='structures_reference_site', to='animateurs.qualification'),
        ),
        migrations.RunPython(configurer_responsabilites, migrations.RunPython.noop),
    ]
