# Generated by Django 6.0.8 on 2026-09-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0112_regles_eligibilite_responsabilites'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=9, unique=True, verbose_name='libellé')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('statut', models.CharField(choices=[('PREPARATION', 'En préparation'), ('ACTIVE', 'Active'), ('CLOTUREE', 'Clôturée')], default='PREPARATION', max_length=11)),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='date de clôture')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
                'ordering': ('-date_debut', '-date_fin', 'libelle'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'ACTIVE')), fields=('statut',), name='annee_scolaire_unique_active', violation_error_message='Une année scolaire est déjà active.'), models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='annee_scolaire_dates_coherentes')],
            },
        ),
    ]
