# Generated by Django 6.0.8 on 2026-09-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0114_initialiser_annee_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
