# Generated by Django 6.0.8 on 2026-09-10 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0115_animateur_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='definitions_groupes_locales', to='animateurs.centre', verbose_name='centre du groupe local'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='portee',
            field=models.CharField(choices=[('LOCAL', 'Local à un site'), ('PARTAGE', 'Partagé entre plusieurs sites')], default='PARTAGE', max_length=7),
        ),
        migrations.AddField(
            model_name='parametresstructure',
            name='multisite',
            field=models.BooleanField(default=True, verbose_name='fonctionnement multisite'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='cle_unique',
            field=models.CharField(default='', editable=False, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='groupe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('centre__isnull', False), ('portee', 'LOCAL')), models.Q(('centre__isnull', True), ('portee', 'PARTAGE')), _connector='OR'), name='groupe_portee_centre_coherent'),
        ),
        migrations.AddConstraint(
            model_name='groupe',
            constraint=models.UniqueConstraint(condition=models.Q(('portee', 'PARTAGE')), fields=('cle_unique',), name='groupe_partage_nom_unique'),
        ),
        migrations.AddConstraint(
            model_name='groupe',
            constraint=models.UniqueConstraint(condition=models.Q(('portee', 'LOCAL')), fields=('centre', 'cle_unique'), name='groupe_local_nom_unique_par_centre'),
        ),
    ]
