# Generated by Django 6.0.8 on 2026-09-12

from django.db import migrations, models


def classer_documents_existants(apps, schema_editor):
    """Classe sans perte les programmes historiques dans leur nouvelle catégorie."""
    Document = apps.get_model("animateurs", "Document")
    Document.objects.filter(type_document="programme_activites").update(
        categorie="pedagogie_activites",
        important=False,
        archive_le=None,
    )
    Document.objects.exclude(type_document="programme_activites").update(
        categorie="autre",
        important=False,
        archive_le=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("animateurs", "0116_portee_groupes_multisite"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="archive_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("pedagogie_activites", "Pédagogie & activités"),
                    ("organisation_planning", "Organisation & planning"),
                    ("protocoles_securite", "Protocoles & sécurité"),
                    ("administratif", "Administratif"),
                    ("autre", "Autre"),
                ],
                db_index=True,
                default="autre",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="important",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(classer_documents_existants, migrations.RunPython.noop),
    ]
