# Generated by Django 6.0.8 on 2026-09-21

from django.db import migrations, models
import django.db.models.deletion


CATEGORIES_INITIALES = (
    ("pedagogie_activites", "Pédagogie & activités", 1),
    ("organisation_planning", "Organisation & planning", 2),
    ("protocoles_securite", "Protocoles & sécurité", 3),
    ("administratif", "Administratif", 4),
    ("autre", "Autre", 5),
)


def creer_categories_et_rattacher_documents(apps, schema_editor):
    CategorieDocument = apps.get_model("animateurs", "CategorieDocument")
    Document = apps.get_model("animateurs", "Document")
    categories_par_code = {}

    for code, nom, ordre in CATEGORIES_INITIALES:
        categorie, _ = CategorieDocument.objects.get_or_create(
            code=code,
            defaults={"nom": nom, "ordre": ordre, "active": True},
        )
        categories_par_code[code] = categorie

    valeurs_existantes = set(Document.objects.values_list("categorie", flat=True).distinct())
    valeurs_inconnues = valeurs_existantes.difference(categories_par_code)
    if valeurs_inconnues:
        raise RuntimeError(
            "Catégories Document historiques inconnues : "
            + ", ".join(sorted(valeurs_inconnues))
        )

    for code, categorie in categories_par_code.items():
        Document.objects.filter(categorie=code).update(categorie_ref=categorie)


class Migration(migrations.Migration):

    dependencies = [
        ("animateurs", "0117_document_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=100)),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "catégorie de document",
                "verbose_name_plural": "catégories de documents",
                "ordering": ("ordre", "nom"),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="categorie_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Référence temporaire pendant la migration des catégories documentaires.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="animateurs.categoriedocument",
            ),
        ),
        migrations.RunPython(creer_categories_et_rattacher_documents, migrations.RunPython.noop),
    ]
