# Generated by Django 5.2.15 on 2026-09-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0118_categoriedocument_et_reference_temporaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='categorie',
        ),
    ]
