# Generated by Django 6.0.8 on 2026-09-23 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0121_destinataire_publication_instantane'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementAffectationPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=2000)),
                ('instantane_affectations', models.JSONField(blank=True, default=list)),
                ('envoye_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='animateurs.destinatairepublicationaffectation')),
            ],
            options={
                'verbose_name': 'signalement sur affectation publiée',
                'verbose_name_plural': 'signalements sur affectations publiées',
                'ordering': ('envoye_le', 'pk'),
            },
        ),
    ]
