# Generated by Django 6.0.8 on 2026-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0122_signalement_affectation_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatairepublicationaffectation',
            name='instantane_affectations_confirmees',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
