# Generated by Django 6.0.8 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animateurs", "0123_confirmations_affectations_detaillees"),
    ]

    operations = [
        migrations.AddField(
            model_name="destinatairepublicationaffectation",
            name="instantane_affectations_est_fige",
            field=models.BooleanField(default=False),
        ),
    ]
