# Generated by Django 6.0.8 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animateurs", "0124_destinataire_publication_instantane_est_fige"),
    ]

    operations = [
        migrations.AddField(
            model_name="destinatairepublicationaffectation",
            name="annulation_notifiee_le",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="destinatairepublicationaffectation",
            name="annulation_prise_en_compte_le",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
