# Generated by Django 6.0.8 on 2026-10-09 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0126_destinataire_publication_instantane_modifie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('ouverte', 'Ouverte'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], db_index=True, default='brouillon', max_length=16)),
                ('date_limite_reponse', models.DateField(blank=True, null=True)),
                ('validation_direction_requise', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('ouverte_le', models.DateTimeField(blank=True, null=True)),
                ('cloturee_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes_disponibilites_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'campagne de disponibilités',
                'verbose_name_plural': 'campagnes de disponibilités',
                'ordering': ('-cree_le', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CampagneDisponibiliteBloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=140)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='animateurs.campagnedisponibilite')),
            ],
            options={
                'verbose_name': 'bloc de campagne de disponibilités',
                'verbose_name_plural': 'blocs de campagne de disponibilités',
                'ordering': ('ordre', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CampagneDisponibiliteDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='animateurs.campagnedisponibilitebloc')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='animateurs.campagnedisponibilite')),
                ('periode_scolaire_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dates_campagnes_disponibilites', to='animateurs.periodescolaire')),
            ],
            options={
                'verbose_name': 'date de campagne de disponibilités',
                'verbose_name_plural': 'dates de campagne de disponibilités',
                'ordering': ('date', 'ordre', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DemandeDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('premiere_saisie', 'Première saisie'), ('modification', 'Modification')], max_length=20)),
                ('statut', models.CharField(choices=[('a_renseigner', 'À renseigner'), ('brouillon', 'Brouillon'), ('envoyee', 'Réponse envoyée'), ('a_corriger', 'À corriger'), ('validee', 'Validée'), ('refusee', 'Refusée')], db_index=True, default='a_renseigner', max_length=16)),
                ('commentaire_animateur', models.TextField(blank=True)),
                ('commentaire_direction', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('envoyee_le', models.DateTimeField(blank=True, null=True)),
                ('traitee_le', models.DateTimeField(blank=True, null=True)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_disponibilites', to='animateurs.animateur')),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='animateurs.campagnedisponibilite')),
                ('demande_precedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions_suivantes', to='animateurs.demandedisponibilite')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_disponibilites_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande de disponibilités',
                'verbose_name_plural': 'demandes de disponibilités',
                'ordering': ('-cree_le', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PropositionDisponibiliteDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('est_disponible', models.BooleanField(default=False)),
                ('etait_disponible', models.BooleanField()),
                ('date_campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propositions', to='animateurs.campagnedisponibilitedate')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='animateurs.demandedisponibilite')),
            ],
            options={
                'verbose_name': 'proposition de disponibilité par date',
                'verbose_name_plural': 'propositions de disponibilité par date',
                'ordering': ('date', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='campagnedisponibilitedate',
            constraint=models.UniqueConstraint(fields=('campagne', 'date'), name='unique_date_campagne_disponibilite'),
        ),
        migrations.AddConstraint(
            model_name='demandedisponibilite',
            constraint=models.UniqueConstraint(condition=models.Q(('campagne__isnull', False)), fields=('campagne', 'animateur'), name='unique_destinataire_campagne_dispo'),
        ),
        migrations.AddConstraint(
            model_name='propositiondisponibilitedate',
            constraint=models.UniqueConstraint(fields=('demande', 'date'), name='unique_proposition_dispo_demande_date'),
        ),
    ]
