# Generated by Django 6.0.8 on 2026-10-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0127_campagnedisponibilite_campagnedisponibilitebloc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagnedisponibilite',
            name='destinataires',
            field=models.ManyToManyField(blank=True, related_name='campagnes_disponibilites', to='animateurs.animateur'),
        ),
    ]
