# Generated by Django 6.0.8 on 2026-10-09 18:55

from django.db import migrations, models


def migrer_est_disponible_vers_creneau(apps, schema_editor):
    Proposition = apps.get_model("animateurs", "PropositionDisponibiliteDate")
    Proposition.objects.filter(est_disponible=True).update(creneau="journee")
    Proposition.objects.filter(est_disponible=False).update(creneau="indisponible")


def migrer_creneau_vers_est_disponible(apps, schema_editor):
    Proposition = apps.get_model("animateurs", "PropositionDisponibiliteDate")
    Proposition.objects.filter(creneau="journee").update(est_disponible=True)


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0128_campagnedisponibilite_destinataires'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagnedisponibilitebloc',
            name='mode_saisie',
            field=models.CharField(choices=[('journee', 'Journée'), ('demi_journee', 'Demi-journée')], default='journee', max_length=16),
        ),
        migrations.AddField(
            model_name='propositiondisponibilitedate',
            name='creneau',
            field=models.CharField(choices=[('non_renseigne', 'Non renseigné'), ('indisponible', 'Indisponible'), ('journee', 'Journée entière'), ('matin', 'Matin'), ('apres_midi', 'Après-midi')], default='non_renseigne', max_length=16),
        ),
        migrations.RunPython(migrer_est_disponible_vers_creneau, migrer_creneau_vers_est_disponible),
        migrations.RemoveField(
            model_name='propositiondisponibilitedate',
            name='est_disponible',
        ),
    ]
