# Generated by ChatGPT for animateurs app on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0007_centre_effectif_cible'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='animateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='animateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
