# Generated by Django 5.2.15 on 2026-07-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0020_remove_disponibilite_dispo_fin_apres_debut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='heure_fin',
        ),
    ]
