# Generated by Django 5.2.15 on 2026-07-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0022_evenement_jours_ouverts_dates_exclues'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvoiEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('nombre_destinataires', models.PositiveIntegerField(default=0)),
                ('nombre_envoyes', models.PositiveIntegerField(default=0)),
                ('nombre_echecs', models.PositiveIntegerField(default=0)),
                ('mode_test', models.BooleanField(default=False)),
                ('documents', models.ManyToManyField(blank=True, related_name='envois_email', to='animateurs.document')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DestinataireEnvoiEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec')], max_length=10)),
                ('erreur', models.TextField(blank=True, default='')),
                ('date_traitement', models.DateTimeField(auto_now_add=True)),
                ('animateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_recus', to='animateurs.animateur')),
                ('envoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinataires', to='animateurs.envoiemail')),
            ],
            options={
                'ordering': ['prenom', 'nom', 'email'],
                'constraints': [models.UniqueConstraint(fields=('envoi', 'email'), name='unique_destinataire_par_envoi_email')],
            },
        ),
    ]
