# Generated by Django 5.2.15 on 2026-07-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0023_envoiemail_destinataireenvoiemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoiemail',
            name='documents_titres',
            field=models.JSONField(default=list, help_text='Copie des titres au moment de l’envoi, conservée si un document est supprimé.'),
        ),
    ]
