# Generated by Django 5.2.15 on 2026-07-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0027_groupes_simplifies'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateur',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animateur',
            name='numero_securite_sociale',
            field=models.CharField(blank=True, help_text='Numéro avec ou sans espaces (15 chiffres, clé comprise).', max_length=21, verbose_name='numéro de sécurité sociale'),
        ),
        migrations.AddField(
            model_name='animateur',
            name='paie_jour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant brut ou net selon la convention retenue par l'association.", max_digits=8, null=True, verbose_name='paie par jour'),
        ),
    ]
