# Generated by Django 5.2.15 on 2026-07-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0040_communicationanimateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunicationAnimateur',
        ),
    ]
