# Generated by Django 5.2.15 on 2026-07-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0050_effectifenfantsjour_enfants_par_animateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='enfants_par_animateur_defaut',
            field=models.PositiveSmallIntegerField(default=8, help_text='Ratio proposé automatiquement dans le Planning, par exemple 8 pour 1 animateur pour 8 enfants.', verbose_name='nombre d’enfants par animateur par défaut'),
        ),
    ]
