# Generated by Django 5.2.15 on 2026-07-21 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateurs', '0063_horaireaffectationjour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilImportEffectifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('configuration', models.JSONField(default=dict)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils_import_effectifs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "profil d'import d'effectifs",
                'verbose_name_plural': "profils d'import d'effectifs",
                'ordering': ('nom',),
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'nom'), name='unique_profil_import_effectifs_par_utilisateur')],
            },
        ),
    ]
